title: "[ADR_000] <タイトル>"
labels: ["ADR", "Proposed"]
body:
  - type: dropdown
    id: status
    attributes:
      label: ステータス
      description: |
        ADRのステータスを選択します
        レビュー依頼を出す場合はProposed
        下書きの場合はDraftを選択
      options:
        - Draft
        - Proposed
        - Accepted
        - Rejected
        - Deprecated
        - Superseded
      default: 1
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: コンテキスト
      description: "決定をした状況を書きます（利用中の技術との兼合いや組織や体制、ビジネス面の時間的な制約）"
      value:
    validations:
      required: true

  - type: textarea
    id: decision
    attributes:
      label: 決定
      description: "決定とその根拠と、他の採用を見送った候補とその課題を書きます"
      value:
    validations:
      required: true

  - type: textarea
    id: influence
    attributes:
      label: 影響
      description: "決定による影響を書きます"
      value:
    validations:
      required: true

  - type: textarea
    id: compliance
    attributes:
      label: コンプライアンス
      description: "決定による影響を書きます"
      value:
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: 参考情報
      description: "参考情報のリンクを張ります"
      value:

  - type: textarea
    id: remarks
    attributes:
      label: 備考
      description: "その他補足があれば書きます"
      value:
